version: '3'
services:
  cpit.wiki:
    image: cpit.wiki
    build: ./ 
    container_name: cpit.wiki
    restart: always
    hostname: cpit.wiki
    ports:
      - 80:8080
    volumes:
      - './:/src'
    networks:
      - cpit-network
    command: yarn docs:dev

networks:
  cpit-network:
    external: true